#!/bin/bash
mkdir bin
javac -d bin -sourcepath tests -cp spreadsheets.jar:lib/hamcrest-core-1.3.jar:lib/junit-4.11.jar tests/com/v1ct04/*/*/*.java tests/com/v1ct04/*/*.java
java -cp bin/:spreadsheets.jar:lib/hamcrest-core-1.3.jar:lib/junit-4.11.jar org.junit.runner.JUnitCore
rm -rf bin